import {
  existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, symlinkSync, writeFileSync, chmodSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { emit, fail, type Ctx } from "./cli";
import { loadPack } from "./pack";

interface Action {
  kind: "registry" | "symlink" | "shim";
  target: string;
  detail: string;
}

function linkState(target: string, source: string): "absent" | "ours" | "conflict" {
  let st;
  try {
    st = lstatSync(target);
  } catch {
    return "absent";
  }
  if (st.isSymbolicLink() && readlinkSync(target) === source) return "ours";
  return "conflict";
}

export function runInstall(ctx: Ctx, dirArg: string, opts: { dryRun: boolean }): void {
  const pack = loadPack(dirArg);
  const home = homedir();
  const plan: Action[] = [];
  const conflicts: string[] = [];

  const regFile = join(home, ".pakt", "packs.json");
  plan.push({ kind: "registry", target: regFile, detail: `register ${pack.manifest.name} → ${pack.dir}` });

  const skillTargets = [join(home, ".claude", "skills"), join(home, ".agents", "skills")];
  const links: Array<{ source: string; target: string }> = [];
  for (const s of pack.skills) {
    const source = join(pack.dir, "skills", s);
    for (const base of skillTargets) {
      const target = join(base, s);
      const state = linkState(target, source);
      if (state === "conflict") conflicts.push(target);
      if (state !== "ours") links.push({ source, target });
      plan.push({ kind: "symlink", target, detail: state === "ours" ? "already linked" : `→ ${source}` });
    }
  }

  const shims: Array<{ path: string; content: string }> = [];
  if (pack.manifest.bin) {
    const entryAbs = resolve(pack.dir, pack.manifest.bin.entry);
    const shimPath = join(home, ".local", "bin", pack.manifest.bin.name);
    const content = `#!/bin/sh\n# generated by pakt install (${pack.manifest.name})\nexec bun "${entryAbs}" "$@"\n`;
    shims.push({ path: shimPath, content });
    plan.push({ kind: "shim", target: shimPath, detail: `exec bun ${entryAbs}` });
  }
  // Self-shim the toolchain so the SKILL.md fallback line (`pakt x <pack> -- ...`,
  // spec §4 MUST) actually resolves for installed users.
  const paktMain = new URL("./main.ts", import.meta.url).pathname;
  shims.push({
    path: join(home, ".local", "bin", "pakt"),
    content: `#!/bin/sh\n# generated by pakt install (toolchain self-shim)\nexec bun "${paktMain}" "$@"\n`,
  });
  plan.push({ kind: "shim", target: join(home, ".local", "bin", "pakt"), detail: `exec bun ${paktMain} (self)` });
  for (const s of shims) {
    if (existsSync(s.path) && readFileSync(s.path, "utf8") !== s.content) conflicts.push(s.path);
  }

  if (opts.dryRun) {
    emit(ctx, { dryRun: true, plan, conflicts }, () =>
      ["plan:", ...plan.map((a) => `  ${a.kind.padEnd(8)} ${a.target}  (${a.detail})`),
        ...(conflicts.length ? ["conflicts:", ...conflicts.map((c) => `  ${c}`)] : [])].join("\n"));
    return;
  }

  if (conflicts.length > 0) {
    fail(ctx, 2, "install conflicts", `these targets exist and are not pakt-managed: ${conflicts.join(", ")}`,
      "remove or rename them, then re-run install");
  }

  mkdirSync(dirname(regFile), { recursive: true });
  const registry = existsSync(regFile) ? JSON.parse(readFileSync(regFile, "utf8")) : {};
  registry[pack.manifest.name] = { dir: pack.dir, bin: pack.manifest.bin?.name ?? null, version: pack.manifest.version };
  writeFileSync(regFile, JSON.stringify(registry, null, 2) + "\n");

  for (const l of links) {
    mkdirSync(dirname(l.target), { recursive: true });
    symlinkSync(l.source, l.target);
  }
  for (const s of shims) {
    mkdirSync(dirname(s.path), { recursive: true });
    writeFileSync(s.path, s.content);
    chmodSync(s.path, 0o755);
  }

  emit(ctx, { installed: pack.manifest.name, plan }, () =>
    `installed ${pack.manifest.name}@${pack.manifest.version} (${plan.length} actions)`);
}
